# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245a5ba0392dd0146a92db13c1b6a9dbdba0cedcfb8d90f290768910cb4ad550f62dde49c903cb6f6bb2ef57016812ed4ad15e876ae454251b4fadb8dd5cc710

test:
  secret_key_base: f6ff0257fbe2434f373b98bc0b6fea6c2c012b05093c69c48a905c13c005166e6403da213a800771a048260c8caaa13bdd13b4eb262381eee68137967626f1f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
